
# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{ $fullName := include "k8sCI.fullname" . }}
{{ $labels := include "k8sCI.labels" . }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $fullName }}-cleaner-cronjob"
  labels:
    {{- $labels | nindent 4 }}
spec:
  schedule: {{ .Values.cleaner.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "{{ $fullName }}"
          volumes:
          - name: workspace
            emptyDir: {}
          containers:
          - name: trigger
            image: gcr.io/tekton-releases/dogfooding/tkn
            command:
              - /bin/sh
            args:
              - -ce
              - |
                set -ex
                # A safety check, to avoid deleting too much!
                if [[ {{ .Values.cleaner.maxJobsToKeep }} -eq 0 || {{ .Values.cleaner.maxJobsToKeep }} == "" ]]; then
                  echo "This task cannot be used to delete *all* resources from a cluster" >&2
                  echo "Please specifcy a value for keep > 0"
                  exit 1
                fi
                # Cleanup pipelineruns first, as this will delete tasksruns too
                tkn pr delete -n {{ .Release.Namespace }} --keep {{ .Values.cleaner.maxJobsToKeep }}
                # Keep double the amount of tr, for standalone trs
                tkn tr delete -n {{ .Release.Namespace }}  --keep {{ mul 2 .Values.cleaner.maxJobsToKeep }} #X2
          restartPolicy: Never
