apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ include "k8sCI.fullname" . }}-check-release-gh
  labels:
    {{- include "k8sCI.labels" . | nindent 4 }}
spec:
  resources:
    inputs:
    - name: git-repo
      type: git
  params:
    - name: org
    - name: repo
    - name: git_sha
    - name: ref
    - name: image
  steps:
  - name: check-release-github
    image: "$(params.image)"
    workingDir: "/workspace/git-repo"
    env:
      - name: GITHUB_USER
        valueFrom:
          secretKeyRef:
            name: {{ include "k8sCI.fullname" . }}
            key: github-user
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: {{ include "k8sCI.fullname" . }}
            key: github-token
    command:
      - "bash"
    args:
      - "-cx"
      - |
        export STATE=$(cat /tekton/home/status)
        export DESCRIPTION=$(cat /tekton/home/description)
        export META_REPO_OWNER=$(params.org)
        export META_REPO_NAME=$(params.repo)
        export VERSION=$(make version)
        check-github-release $VERSION;
        RESULT=$?
        [ $RESULT -eq 0 ] && echo "success" > /tekton/home/status || echo "failure" > /tekton/home/status;
        [ $RESULT -ne 0 ] && echo "github release already exists for ${VERSION} - please increment version." > /tekton/home/description;
        exit 0;
    volumeMounts:
    - mountPath: /tekton/home
      name: home
