apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: make-tf-plan
spec:
  steps:
    - name: build
      image: 167742443741.dkr.ecr.us-west-2.amazonaws.com/node:12.13.0-build
      command:
        - make
      args:
        - "tf-plan"
