apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-non-prod
spec:
  resources:
    inputs:
    - name: git-repo
      type: git
  params:
    - name: org
    - name: repo
    - name: git_sha
    - name: ref
    - name: image
  steps:
    - name: build
      image: 167742443741.dkr.ecr.us-west-2.amazonaws.com/node:12.13.0-build
      command:
        - make
      args:
        - "docker-publish"
