{{- $fullName := include "k8sCI.fullname" . -}}

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ include "k8sCI.fullname" . }}-run-command-gitea
  labels:
    {{- include "k8sCI.labels" . | nindent 4 }}
spec:
  resources:
    inputs:
    - name: git-repo
      type: git
  params:
    - name: org
    - name: repo
    - name: git_sha
    - name: ref
    - name: image
    - name: command
    - name: htmlurl
  results:
    - name: status
    - name: description
  steps:
    - name: run
      image: "$(params.image)"
      workingDir: "/workspace/git-repo"
      env:
      {{- range .Values.pipelineEnvSecrets }}
      - name: {{ .name }}
        valueFrom:
          secretKeyRef:
            name: {{ $fullName }}
            key: {{ .name }}
      {{- end }}
      command:
        - "bash"
      args:
        - "-cx"
        - |
          set +e;
          $(params.command);
          RESULT=$?
          [ $RESULT -eq 0 ] && echo "success" > /tekton/home/status || echo "failure" > /tekton/home/status;
          [ $RESULT -eq 0 ] && echo "build succeeded." > /tekton/home/description || echo "build failed." > /tekton/home/description
          exit 0;
      volumeMounts:
      - mountPath: /tekton/home
        name: home
      - mountPath: /var/lib/docker
        name: dind-storage
      - mountPath: /var/run/
        name: dind-socket
    - name: post-commit-status-gitea
      image: "$(params.image)"
      env:
      {{- range .Values.pipelineEnvSecrets }}
      - name: {{ .name }}
        valueFrom:
          secretKeyRef:
            name: {{ $fullName }}
            key: {{ .name }}
      {{- end }}
      command:
        - "bash"
      args:
        - "-cx"
        - |
          # pending,success,error,failure,warning
          curl -X POST {{ .Values.gitSources.gitea.apiEndPoint}}/repos/$(params.org)/$(params.repo)/statuses/$(params.git_sha) \
          -H "accept: application/json" \
          -H "Authorization: token ${GITEA_TOKEN}" \
          -H "Content-Type: application/json" -i -k -d "{\
            \"context\": \"k8sCI\",\
            \"description\": \"$(cat /tekton/home/description)\",\
            \"state\": \"$(cat /tekton/home/status)\",\
            \"target_url\": \"{{ .Values.ingress.host }}/dashboard\"\
          }"
      volumeMounts:
      - mountPath: /tekton/home
        name: home
    {{- if .Values.notifications.slackWebhook }}
    - name: slack-notify
      image: "technosophos/slack-notify"
      env:
        - name: SLACK_WEBHOOK
          value: {{ .Values.notifications.slackWebhook }}
        - name: SLACK_USERNAME
          value: "{{ $fullName }}"
      workingDir: "/workspace/git-repo"
      command:
        - "bash"
      args:
        - "-cx"
        - |
          export SLACK_TITLE="gitea: $(params.org)/$(params.repo) $(cat /tekton/home/status)"
          export SLACK_MESSAGE="$(params.htmlurl) $(cat /tekton/home/description) ref=$(params.ref)"
          [ "$STATE" != "success" ] && export SLACK_COLOR="danger" || export SLACK_COLOR="success"
          /slack-notify
      volumeMounts:
      - mountPath: /tekton/home
        name: home
      {{- end }}
  sidecars:
  - image: docker:18.05-dind
    name: server
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /var/lib/docker
        name: dind-storage
      - mountPath: /var/run/
        name: dind-socket
  volumes:
    - name: home
      emptyDir: {}
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}
