apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ include "k8sCI.fullname" . }}-post-status-github
  labels:
    {{- include "k8sCI.labels" . | nindent 4 }}
spec:
  resources:
    inputs:
    - name: git-repo
      type: git
  params:
    - name: org
    - name: repo
    - name: git_sha
    - name: ref
    - name: image
    - name: pr-url
  results:
    - name: status
    - name: description
  steps:
    - name: post-status-github
      image: "$(params.image)"
      workingDir: "/workspace/git-repo"
      env:

      command:
        - "bash"
      args:
        - "-cx"
        - |
          echo "posting status: status to github";
          export AWS_DEFAULT_REGION=us-west-2;
          export GITHUB_USER=$(aws ssm get-parameters --with-decryption  --names /cicd/github_user | jq .Parameters[0].Value | sed -e 's/^"//' -e 's/"$//');
          export GITHUB_TOKEN=$(aws ssm get-parameters --with-decryption  --names /cicd/github_token | jq .Parameters[0].Value | sed -e 's/^"//' -e 's/"$//');
          export STATE=$(cat /tekton/home/status)
          export DESCRIPTION=$(cat /tekton/home/description)
          curl -XPOST -u "${GITHUB_USER}:${GITHUB_TOKEN}" -d "{ \"state\":\"${STATE}\", \"description\": \"${DESCRIPTION}\", \"context\":\"watchdog-cicd\"}" https://api.github.com/repos/$(params.org)/$(params.repo)/statuses/$(params.git_sha)
      volumeMounts:
      - mountPath: /tekton/home
        name: home
    - name: report-if-error
      image: "$(params.image)"
      workingDir: "/workspace/git-repo"
      env:
        - name: SLACK_WEBHOOK
          valueFrom:
            secretKeyRef:
              name: {{ include "k8sCI.fullname" . }}
              key: slack-webhook
      command:
        - "bash"
      args:
        - "-cx"
        - |
          echo "slack notifcation if error";
          export STATE=$(cat /tekton/home/status)
          export DESCRIPTION=$(cat /tekton/home/description)
          export VERSION=$(make version || echo "unversioned")
          [ "$STATE" != "success" ] && export color="danger" || export color="danger"

          DATA="{\
              \"attachments\": [\
                  {\
                      \"fallback\": \"$(params.org)/$(params.repo) - $STATEversion=${VERSION}\",
                      \"title\": \"$(params.org)/$(params.repo) - $STATE\",
                      \"title_link\": \"$CODEBUILD_BUILD_URL\",
                      \"color\": \"$color\",
                      \"text\": \"$1\n\n<$(params.pr-url)/|Open>\"
                  }\
              ]\
          }"


          curl -s -X POST -H 'Content-type: application/json' --data "$DATA" $SLACK_WEBHOOK > /dev/null
      volumeMounts:
      - mountPath: /tekton/home
        name: home
  volumes:
    - name: home
      emptyDir: {}
