apiVersion:  triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: {{ include "k8sCI.fullname" . }}-pr-github-tb
  labels:
    {{- include "k8sCI.labels" . | nindent 4 }}
spec:
  params:
  - name: gitrevision
    value: $(body.pull_request.head.sha)
  - name: gitrepositorysshurl
    value: $(body.pull_request.head.repo.ssh_url)
  - name: contenttype
    value: $(header.Content-Type)
  - name: repo
    value: $(body.pull_request.head.repo.name)
  - name: org
    value: $(body.pull_request.head.repo.owner.login)
  - name: ref
    value: $(body.pull_request.head.ref)
  - name: type
    value: github
  - name: htmlurl
    value: $(body.pull_request.head.repo.html_url)
