apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8sCI.fullname" . }}
type: Opaque
data:
  githubUser: {{ .Values.secrets.githubUser | b64enc | quote }}
  giteaUser:  {{ .Values.secrets.giteaUser | b64enc | quote }}
  githubToken:  {{ .Values.secrets.githubToken | b64enc | quote }}
  giteaToken:  {{ .Values.secrets.giteaToken | b64enc | quote }}
  sshKey: {{ .Values.secrets.sshKey | b64enc | quote }}
  slackWebhook: {{ .Values.slackNotify.slackWebhook | b64enc | quote}}
