{{- $fullName := include "k8sCI.fullname" . -}}
{{- $labels := include "k8sCI.labels" . -}}

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: "{{ $fullName }}-cd"
  labels:
    {{- $labels | nindent 4 }}
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositorysshurl
    description: "The git repo url"
  - name: org
    description: "The github/gitea org of the PR"
  - name: repo
    description: "The github/gitea repo of the PR"
  - name: message
    description: "Notification message text"
    default: build
  - name: ref
    description: "git ref"
  - name: image
    description: "run image"
  - name: ciCommands
    description: "continuous integration command"
  - name: ciStatuses
    description: "continuous integration statuses"
  - name: cdCommands
    description: "continuous delivery command"
  - name: cdStatuses
    description: "continuous delivery statuses"
  - name: type
    description: "type of pipeline: ex gitea/github"
  - name: htmlurl
    description: repo url
  - name: pipelineName
    description: Name of the pipeline being run
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: cd-
    spec:
      serviceAccountName: "{{ $fullName }}"
      pipelineSpec:
        resources:
          - name: source-repo
            type: git
        tasks:
          - name: runtask-cd
            when:
            - input: "$(tt.params.ref)"
              operator: in
              values: ["refs/heads/master", "refs/heads/main"]
            params:
              - name: org
                value: $(tt.params.org)
              - name: repo
                value: $(tt.params.repo)
              - name: git_sha
                value: $(tt.params.gitrevision)
              - name: ref
                value: $(tt.params.ref)
              - name: image
                value: $(tt.params.image)
              - name: commands
                value: $(tt.params.cdCommands)
              - name: statuses
                value: $(tt.params.cdStatuses)
              - name: htmlurl
                value: $(tt.params.htmlurl)
              - name: pipelineType
                value: "Continuous Deployment"
              - name: pipelineName
                value: $(tt.params.pipelineName)
            resources:
              inputs:
                - name: git-repo
                  resource: source-repo
            taskRef:
              name: "{{ $fullName }}-run-command-$(params.type)"
      resources:
        - name: source-repo
          resourceSpec:
            type: git
            params:
            - name: revision
              value: $(params.gitrevision)
            - name: url
              value: $(params.gitrepositorysshurl)
