{{- $fullName := include "k8sCI.fullname" . -}}
{{- $labels := include "k8sCI.labels" . -}}

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: "{{ $fullName }}-ci"
  labels:
    {{- $labels | nindent 4 }}
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositorysshurl
    description: "The git repo url"
  - name: org
    description: "The github/gitea org of the PR"
  - name: repo
    description: "The github/gitea repo of the PR"
  - name: message
    description: "Notification message text"
    default: build
  - name: ref
    description: "git ref"
  - name: image
    description: "run image"
  - name: ciCommands
    description: "continuous integration command"
  - name: ciStatuses
    description: "continuous integration statuses"
  - name: cdCommands
    description: "continuous delivery command"
  - name: cdStatuses
    description: "continuous delivery statuses"
  - name: type
    description: "type of pipeline: ex gitea/github"
  - name: htmlurl
    description: repo url
  - name: pipelineName
    description: Name of the pipeline being run
  resourcetemplates:
  - apiVersion:  tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-pipeline-run-
    spec:
      serviceAccountName: "{{ $fullName }}"
      pipelineSpec:
        resources:
          - name: source-repo
            type: git
        tasks:
          - name: ci
            params:
              - name: org
                value: $(params.org)
              - name: repo
                value: $(params.repo)
              - name: git_sha
                value: $(params.gitrevision)
              - name: ref
                value: $(params.ref)
              - name: image
                value: $(params.image)
              - name: commands
                value: $(params.ciCommands)
              - name: statuses
                value: $(params.ciStatuses)
              - name: htmlurl
                value: $(params.htmlurl)
              - name: pipelineType
                value: "Continuous Intgegration"
              - name: pipelineName
                value: $(params.pipelineName)
            resources:
              inputs:
                - name: git-repo
                  resource: source-repo
            taskRef:
              name: "{{ $fullName }}-run-command-$(params.type)"
            conditions:
            - conditionRef: "{{ $fullName }}-non-master-branch"
              params:
                - name: ref
                  value: $(params.ref)
        resources:
        - name: source-repo
          resourceSpec:
            type: git
            params:
            - name: revision
              value: $(params.gitrevision)
            - name: url
              value: $(params.gitrepositorysshurl)
