{{- $fullName := include "k8sCI.fullname" . -}}
{{- $labels := include "k8sCI.labels" . -}}
{{- range .Values.build_images }}

apiVersion:  triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: "{{ $fullName }}-image-{{ .name }}-tb"
  labels:
    {{- $labels | nindent 4 }}
spec:
  params:
  - name: image
    value: {{ .image }}

---
{{- end }}
