{{- $fullName := include "k8sCI.fullname" . -}}
{{- $labels := include "k8sCI.labels" . -}}
{{- if .Values.gitAuthSsh }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-git-auth
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    {{- $index := 0 -}}
    {{- range .Values.gitAuthSsh.hosts }}
    tekton.dev/git-{{ $index }}: "{{ . }}"
    {{- $index = $index | add1 -}}
    {{- end }}
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ .Values.gitAuthSsh.sshPrivatekey  | b64enc | quote }}
  known_hosts: {{ .Values.gitAuthSsh.known_hosts | b64enc | quote }}
{{- end }}
