apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8sCI.fullname" . }}
  labels:
    {{- include "k8sCI.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.pipelineEnvSecrets }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
  slackWebhook: {{ .Values.notifications.slackWebhook | b64enc | quote }}
  webhookSecretToken: {{ .Values.webhookSecretToken | b64enc | quote }}
