{{- $fullName := include "k8sCI.fullname" . -}}
{{- $labels := include "k8sCI.labels" . -}}
{{- range .Values.build_images }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: "{{ $fullName }}-gitea-{{ .name }}"
  labels:
    {{- $labels | nindent 4 }}
spec:
  serviceAccountName: {{ $fullName }}
  triggers:
    - name: "{{$fullName }}-gitea-{{ .name }}"
      interceptors:
        - webhook:
            header:
              - name: X-Gitea-Event
                value:
                  - push
            objectRef:
              kind: Service
              name: wh-validate
              apiVersion: v1
              namespace: default
      bindings:
        - name: "{{ $fullName }}-build-gitea-tb"
        - name: "{{ $fullName }}-image-{{ .name }}-tb"
      template:
        name: "{{ $fullName }}-build"

---

{{- end }}
