{{- $fullName := include "k8sCI.fullname" . -}}
{{- $labels := include "k8sCI.labels" . -}}

{{- if .Values.gitSources.gitea }}
{{- range .Values.cicdPipelines }}

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: "{{ $fullName }}-gitea-{{ .name }}"
  labels:
    {{- $labels | nindent 4 }}
spec:
  serviceAccountName: {{ $fullName }}
  triggers:
    - name: "{{$fullName }}-gitea-push-{{ .name }}-ci"
      interceptors:
        - webhook:
            header:
              - name: X-Gitea-Event
                value:
                  - push
            objectRef:
              kind: Service
              name: "{{ $fullName }}-gitea-validate"
              apiVersion: v1
      bindings:
        - ref: "{{ $fullName }}-push-gitea-tb"
        - ref: "{{ $fullName }}-pipeline-{{ .name }}-tb"
      template:
        name: "{{ $fullName }}-ci"
    - name: "{{$fullName }}-gitea-pr-{{ .name }}-ci"
      interceptors:
        - webhook:
            header:
              - name: X-Gitea-Event
                value:
                  - pull_request
            objectRef:
              kind: Service
              name: "{{ $fullName }}-gitea-validate"
              apiVersion: v1
      bindings:
        - ref: "{{ $fullName }}-pr-gitea-tb"
        - ref: "{{ $fullName }}-pipeline-{{ .name }}-tb"
      template:
        name: "{{ $fullName }}-ci"
    - name: "{{$fullName }}-gitea-push-{{ .name }}-cd"
      interceptors:
        - webhook:
            header:
              - name: X-Gitea-Event
                value:
                  - push
            objectRef:
              kind: Service
              name: "{{ $fullName }}-gitea-validate"
              apiVersion: v1
      bindings:
        - ref: "{{ $fullName }}-push-gitea-tb"
        - ref: "{{ $fullName }}-pipeline-{{ .name }}-tb"
      template:
        name: "{{ $fullName }}-cd"
    - name: "{{$fullName }}-gitea-pr-{{ .name }}-cd"
      interceptors:
        - webhook:
            header:
              - name: X-Gitea-Event
                value:
                  - pull_request
            objectRef:
              kind: Service
              name: "{{ $fullName }}-gitea-validate"
              apiVersion: v1
      bindings:
        - ref: "{{ $fullName }}-pr-gitea-tb"
        - ref: "{{ $fullName }}-pipeline-{{ .name }}-tb"
      template:
        name: "{{ $fullName }}-cd"
---

{{- end }}
{{- end }}
