{{- $fullName := include "k8sCI.fullname" . -}}

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ include "k8sCI.fullname" . }}-run-command-gitea
  labels:
    {{- include "k8sCI.labels" . | nindent 4 }}
spec:
  resources:
    inputs:
    - name: git-repo
      type: git
  params:
    - name: org
    - name: repo
    - name: git_sha
    - name: ref
    - name: image
    - name: commands
    - name: statuses
    - name: htmlurl
    - name: pipelineName
    - name: pipelineType
  results:
    - name: description
    - name: output
  steps:
    - name: post-pending-status-gitea
      image: "$(params.image)"
      env:
      {{- range .Values.pipelineEnvSecrets }}
      - name: {{ .name }}
        valueFrom:
          secretKeyRef:
            name: {{ $fullName }}
            key: {{ .name }}
      {{- end }}
      command:
        - "bash"
      args:
        - "-cx"
        - |
          declare -a STATUSES
          STATUSES=($(params.statuses))

          # extract the protocol
          proto="$(echo $(params.htmlurl) | grep :// | sed -e's,^\(.*://\).*,\1,g')"

          # remove the protocol
          url=$(echo $(params.htmlurl) | sed -e s,$proto,,g)

          # extract the host and port
          hostport=$(echo $url |  cut -d/ -f1)
          API_END_POINT=${proto}${hostport}/api/v1

          for status in "${STATUSES[@]}"
          do
            :
            # pending,success,error,failure,warning
            curl -X POST ${API_END_POINT}/repos/$(params.org)/$(params.repo)/statuses/$(params.git_sha) \
            -H "accept: application/json" \
            -H "Authorization: token ${GITEA_TOKEN}" \
            -H "Content-Type: application/json" -i -k -d "{\
              \"context\": \"${status}\",\
              \"description\": \"pending...\",\
              \"state\": \"pending\",\
              \"target_url\": \"{{ .Values.ingress.host }}/dashboard\"\
            };"
          done
    - name: run
      image: "$(params.image)"
      workingDir: "/workspace/git-repo"
      securityContext:
        privileged: true
      env:
      {{- range .Values.pipelineEnvSecrets }}
      - name: {{ .name }}
        valueFrom:
          secretKeyRef:
            name: {{ $fullName }}
            key: {{ .name }}
      {{- end }}
      - name: GIT-REF
        value: $(params.ref)
      command:
        - "bash"
      args:
        - "-cx"
        - |
          set +e;
          RESULT=0;
          INDEX=0;
          declare -a STATUSES
          STATUSES=($(params.statuses))
          declare -a COMMANDS
          COMMANDS=($(params.commands))
          for command in "${COMMANDS[@]}"
          do
             :
             status=${STATUSES[$INDEX]};
             ${command} &>> /tekton/home/output;
             RESULT=$?;
             [ $RESULT -ne 0 ] && [ "$status" != "" ] && echo "failure" > /tekton/home/status/${status} && break
             [ $RESULT -eq 0 ] && [ "$status" != "" ] && echo "success" > /tekton/home/status/${status}
             ((INDEX++))
          done
          [ $RESULT -eq 0 ] && echo "succeeded." > /tekton/home/description || echo "build failed." > /tekton/home/description;
          cat /tekton/home/output;
          exit 0;
      volumeMounts:
      - mountPath: /tekton/home
        name: home
      - mountPath: /var/lib/docker
        name: dind-storage
      - mountPath: /var/run/
        name: dind-socket
      - mountPath: /root/.ssh
        name: ssh-creds
    - name: post-commit-status-gitea
      image: "$(params.image)"
      env:
      {{- range .Values.pipelineEnvSecrets }}
      - name: {{ .name }}
        valueFrom:
          secretKeyRef:
            name: {{ $fullName }}
            key: {{ .name }}
      {{- end }}
      command:
        - "bash"
      args:
        - "-cx"
        - |
          declare -a STATUSES
          STATUSES=($(params.statuses))
          # extract the protocol
          proto="$(echo $(params.htmlurl) | grep :// | sed -e's,^\(.*://\).*,\1,g')"

          # remove the protocol
          url=$(echo $(params.htmlurl) | sed -e s,$proto,,g)

          # extract the host and port
          hostport=$(echo $url |  cut -d/ -f1)
          API_END_POINT=${proto}${hostport}/api/v1
          for status in "${STATUSES[@]}"
          do
            :
            description="check passed."
            state=$(cat /tekton/home/status/${status})
            [ "$state" != "success" ] && description="check did not pass."
            # pending,success,error,failure,warning
            [ "$status" != "" ] && curl -X POST ${API_END_POINT}/repos/$(params.org)/$(params.repo)/statuses/$(params.git_sha) \
            -H "accept: application/json" \
            -H "Authorization: token ${GITEA_TOKEN}" \
            -H "Content-Type: application/json" -i -k -d "{\
              \"context\": \"$status\",\
              \"description\": \"$description\",\
              \"state\": \"$state\",\
              \"target_url\": \"{{ .Values.ingress.host }}/dashboard\"\
            }"
          done
      volumeMounts:
      - mountPath: /tekton/home
        name: home
    {{- if .Values.notifications.slackWebhook }}
    - name: slack-notify
      image: "$(params.image)"
      env:
        - name: SLACK_WEBHOOK
          valueFrom:
            secretKeyRef:
              name: {{ $fullName }}
              key: slackWebhook
        - name: PIPELINE_RUN
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tekton.dev/pipelineRun']
      workingDir: "/workspace/git-repo"
      command:
        - "bash"
      args:
        - "-cx"
        - |
          declare -a COMMANDS
          COMMANDS=($(params.commands))
          export DESCRIPTION=$(cat /tekton/home/description);
          [ "$DESCRIPTION" != "succeeded." ] && export SYMBOL=":no_entry:" || export SYMBOL=":thumbsup:";
          export SLACK_TITLE="${SYMBOL} gitea Pipeline: $(params.pipelineName) $(params.pipelineType)\n\nStatus: ${STATUS}\n\nRepo: <$(params.htmlurl)|$(params.org)/$(params.repo)>\n\n<{{ .Values.ingress.dashboardURL }}/#/namespaces/cicd/pipelineruns/${PIPELINE_RUN}|build information>";
          export SLACK_MESSAGE="$(printf '%s\n' "${COMMANDS[@]}")\n $DESCRIPTION";
          ## TODO SLACK API too picky with text - figure out how to do a snippet
          # [ "$STATUS" != "success" ] && export SLACK_MESSAGE="\`\`\`$(cat /tekton/home/output | sed "s/\"/\\\"/g" | sed "s/'//g" | sed "s/\`/\\\`/g" )\`\`\`";
          PAYLOAD=$( cat <<EOT
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "$SLACK_TITLE"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "$SLACK_MESSAGE"
                }
              }
            ]
          }
          EOT
          );
          curl -d "$PAYLOAD" -H "Content-Type: application/json" -X POST $SLACK_WEBHOOK
      volumeMounts:
      - mountPath: /tekton/home
        name: home
      {{- end }}
  sidecars:
  - image: docker:18.05-dind
    name: server
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /var/lib/docker
        name: dind-storage
      - mountPath: /var/run/
        name: dind-socket
  - image: "$(params.image)"
    name: init-ssh-creds
    command:
      - "sh"
    args:
      - "-c"
      - |
        cp /secretsDir/*  /root/.ssh
        mv ~/.ssh/ssh-privatekey ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        mkdir -p /tekton/home/status
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    volumeMounts:
      - mountPath: /root/.ssh
        name: ssh-creds
      - mountPath: /secretsDir
        name: git-auth
      - mountPath: /tekton/home
        name: home
  volumes:
    - name: home
      emptyDir: {}
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}
    - name: ssh-creds
      emptyDir: {}
    - name: git-auth
      secret:
        secretName: "{{ $fullName }}-git-auth"
